---
# yamllint disable rule:line-length
name: Python checks
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.py'
            - .github/workflows/python-checks.yml
            - github_action_scripts/python_checks.sh
            - github_action_scripts/python_checks.bat
jobs:
    pip-install-and-tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                python-version: ["3.7", "3.8", "3.9", "3.10"]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: "Python checks: Ubuntu"
              if: matrix.os == 'ubuntu-latest'
              run: ./github_action_scripts/python_checks.sh
            - name: "Python checks: Windows"
              if: matrix.os == 'windows-latest'
              run: |
                python -m venv "%USERPROFILE%\venv"
                %USERPROFILE%\venv\Scripts\activate.bat
                python -VV
                python -m site
                python -m pip install -U pip
                echo dumping pre-installed packages
                python -m pip freeze
                echo installing pip packages
                python -m pip install -e .
                echo running tests
                set CRATE_RUN_WITHOUT_LOCAL_SETTINGS=True
                crate_anon_demo_config > %USERPROFILE%\crate_anon_config.ini
                pytest -v
              shell: cmd
